### ISSUE TITLE
app getting killed in background

### ISSUE THREAD

**Issue by sentinelweb** [sentinelweb/cuer#101]
looks like the service isn't getting foreground status
`adb shell dumpsys activity processes | grep -A 400 -B 20 -i cuer`

see this
https://stackoverflow.com/questions/6645193/foreground-service-being-killed-by-android

- [x] ensure service connection stays foreground
- [x] make disconnect work from service (#77 )
- [ ] cast connection is getting lost while in bg. when click on another item it sets cuttrent locally while old is playing remotely
   - cant reproduce -> might be fixed by -v
- [x] saw the notif dissappear when the video changed (see ex below - pixel 3a)
- [x] check operation when screen turns off and activy was present (i.e. no service active) - should staert service or shuld make service active all the time while connected
   - [ ] would need too make`ChromecastYouTubePlayerContextHolder` support multiple players (activity & notif)? 
      - [ ] easier to make a composite player that holds the collection
   - screeen function was ok - so not modified
- [x] also do #66

**Comment by sentinelweb** [comment]
more links about foreground services

- https://medium.com/@debuggingisfun/android-foregroundservicetype-8857a36f36b9
- https://developer.android.com/guide/components/foreground-services

**Comment by sentinelweb** [comment]
```
2021-01-10 20:18:45.738 17176-17176/uk.co.sentinelweb.cuer.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: uk.co.sentinelweb.cuer.app, PID: 17176
    android.app.RemoteServiceException: Bad notification(tag=null, id=34563) posted from package uk.co.sentinelweb.cuer.app, crashing app(uid=10305, pid=17176): Couldn't inflate contentViewsjava.lang.IndexOutOfBoundsException: Index: 6, Size: 6
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-01-10 20:18:45.739 17176-17176/uk.co.sentinelweb.cuer.app E/Cuer: FATAL Global Exception
    android.app.RemoteServiceException: Bad notification(tag=null, id=34563) posted from package uk.co.sentinelweb.cuer.app, crashing app(uid=10305, pid=17176): Couldn't inflate contentViewsjava.lang.IndexOutOfBoundsException: Index: 6, Size: 6
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-01-10 20:18:45.746 17176-17176/uk.co.sentinelweb.cuer.app I/Process: Sending signal. PID: 17176 SIG: 9
```
