### ISSUE TITLE
crash in cast init

### ISSUE THREAD

**Issue by sentinelweb** [sentinelweb/cuer#137]
- [x] fix below stacktrace
- [x] (left might - be fixed by above) https://console.firebase.google.com/u/0/project/cuer-275020/crashlytics/app/android:uk.co.sentinelweb.cuer.app/issues/8c571dac101360cd0d1d083ef2f005c5?time=last-thirty-days&sessionEventKey=6026297C02CB000165D677DC19F1B6D5_1506788050291956425. 

- [x] (left should be fixed with #127) https://console.firebase.google.com/u/0/project/cuer-275020/crashlytics/app/android:uk.co.sentinelweb.cuer.app/issues/ce9930f1f3d5acb75c59514fe67ba20f?time=last-thirty-days&devices=Google%EF%BF%BFPixel%203a&sessionEventKey=60241FA701990001308A77DC19F1B6D5_1506186833106667299

these two are related (playlist init)
- [x] https://console.firebase.google.com/u/0/project/cuer-275020/crashlytics/app/android:uk.co.sentinelweb.cuer.app/issues/4327fe803111512eecee77008ce8587a?time=last-thirty-days&devices=Google%EF%BF%BFPixel%203a&sessionEventKey=60223D69010F000110FD77DC19F1B6D5_1505759908790820146
- [x] https://console.firebase.google.com/u/0/project/cuer-275020/crashlytics/app/android:uk.co.sentinelweb.cuer.app/issues/1eb62517f1258b929ce5d0c084a38aba?time=last-thirty-days&devices=Google%EF%BF%BFPixel%203a&sessionEventKey=6024EDC900A100010D0177DC19F1B6D5_1506532228740541099
- [ ] catch network timeout exceptions
  - [ ] https://console.firebase.google.com/u/0/project/cuer-275020/crashlytics/app/android:uk.co.sentinelweb.cuer.app/issues/258d0ce6f9b06705cb49b4725e06e1a9?time=last-thirty-days&devices=Google%EF%BF%BFPixel%203a&sessionEventKey=602A66270364000179AA2829C2DE9780_1507996255117668193
  - [ ] below exception (next comment)

```
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property context has not been initialized
        at uk.co.sentinelweb.cuer.app.util.cast.listener.YoutubeCastConnectionListener.setupPlayerListener(YoutubeCastConnectionListener.kt:64)
        at uk.co.sentinelweb.cuer.app.util.cast.listener.YoutubeCastConnectionListener.onChromecastConnected(YoutubeCastConnectionListener.kt:56)
        at com.pierfrancescosoffritti.androidyoutubeplayer.chromecast.chromecastsender.io.infrastructure.ChromecastManager.onCastSessionConnected(ChromecastManager.kt:32)
        at com.pierfrancescosoffritti.androidyoutubeplayer.chromecast.chromecastsender.io.infrastructure.ChromecastManager.restoreSession(ChromecastManager.kt:45)
        at com.pierfrancescosoffritti.androidyoutubeplayer.chromecast.chromecastsender.ChromecastYouTubePlayerContext.onCreate(ChromecastYouTubePlayerContext.kt:24)
        at com.pierfrancescosoffritti.androidyoutubeplayer.chromecast.chromecastsender.ChromecastYouTubePlayerContext.<init>(ChromecastYouTubePlayerContext.kt:18)
        at uk.co.sentinelweb.cuer.app.util.cast.listener.YoutubePlayerContextCreator.createContext(YoutubePlayerContextCreator.kt:24)
        at uk.co.sentinelweb.cuer.app.util.cast.listener.ChromecastYouTubePlayerContextHolder.create(ChromecastYouTubePlayerContextHolder.kt:26)
        at uk.co.sentinelweb.cuer.app.ui.main.MainPresenter.initialiseCastContext(MainPresenter.kt:37)
        at uk.co.sentinelweb.cuer.app.ui.main.MainPresenter.onPlayServicesOk(MainPresenter.kt:32)
        at uk.co.sentinelweb.cuer.app.ui.main.MainActivity$checkPlayServices$1.invoke(MainActivity.kt:89)
        at uk.co.sentinelweb.cuer.app.ui.main.MainActivity$checkPlayServices$1.invoke(MainActivity.kt:33)
        at uk.co.sentinelweb.cuer.app.util.cast.ChromeCastWrapper$checkPlayServices$1.run(ChromeCastWrapper.kt:35)
        at com.pierfrancescosoffritti.androidyoutubeplayer.chromecast.chromecastsender.utils.PlayServicesUtils.checkGooglePlayServicesAvailability(PlayServicesUtils.kt:17)
        at uk.co.sentinelweb.cuer.app.util.cast.ChromeCastWrapper.checkPlayServices(ChromeCastWrapper.kt:34)
        at uk.co.sentinelweb.cuer.app.ui.main.MainActivity.checkPlayServices(MainActivity.kt:86)
        at uk.co.sentinelweb.cuer.app.ui.main.MainPresenter.initialise(MainPresenter.kt:23)
        at uk.co.sentinelweb.cuer.app.ui.main.MainActivity.onCreate(MainActivity.kt:63)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
```

**Comment by sentinelweb** [comment]
`FATAL Global Exception
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : uk.co.sentinelweb.cuer.app.orchestrator.OrchestratorContract$NetException
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at uk.co.sentinelweb.cuer.app.orchestrator.MediaOrchestrator.load(MediaOrchestrator.kt:111)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at uk.co.sentinelweb.cuer.app.orchestrator.MediaOrchestrator$load$2.invokeSuspend(Unknown Source:12)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at android.os.Handler.handleCallback(Handler.java:938)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at android.os.Looper.loop(Looper.java:223)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at android.app.ActivityThread.main(ActivityThread.java:7660)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at java.lang.reflect.Method.invoke(Native Method)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : Caused by: java.io.InterruptedIOException: timeout
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at okhttp3.internal.connection.Transmitter.timeoutExit(Transmitter.kt:105)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at okhttp3.internal.connection.Transmitter.maybeReleaseConnection(Transmitter.kt:295)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at okhttp3.internal.connection.Transmitter.noMoreExchanges(Transmitter.kt:259)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:202)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at java.lang.Thread.run(Thread.java:923)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : Caused by: java.io.IOException: Canceled
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at uk.co.sentinelweb.cuer.net.retrofit.RetrofitBuilder$Companion$PRINT_URL_INTERCEPTOR$1.intercept(RetrofitBuilder.kt:58)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:152)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
(standard input)-02-15 18:55:38.568 31146 31146 E Cuer    : 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:194)
`
