### ISSUE TITLE
service crashes

### ISSUE THREAD

**Issue by sentinelweb** [sentinelweb/cuer#141]
FATAL EXCEPTION: main
 AndroidRuntime: Process: uk.co.sentinelweb.cuer.app, PID: 3638
 AndroidRuntime: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{34f256 u0 uk.co.sentinelweb.cuer.app/.service.cast.YoutubeCastService}
 AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
 AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
 AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
 AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
FATAL Global Exception
(standard input)-02-15 23:13:18.957  3638  3638 E Cuer    : android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{34f256 u0 uk.co.sentinelweb.cuer.app/.service.cast.YoutubeCastService}
(standard input)-02-15 23:13:18.957  3638  3638 E Cuer    : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
(standard input)-02-15 23:13:18.957  3638  3638 E Cuer    : 	at android.os.Handler.dispatchMessage(Handler.java:106)
(standard input)-02-15 23:13:18.957  3638  3638 E Cuer    : 	at android.os.Looper.loop(Looper.java:223)
(standard input)-02-15 23:13:18.957  3638  3638 E Cuer    : 	at android.app.ActivityThread.main(ActivityThread.java:7660)
(standard input)-02-15 23:13:18.957  3638  3638 E Cuer    : 	at java.lang.reflect.Method.invoke(Native Method)
(standard input)-02-15 23:13:18.957  3638  3638 E Cuer    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
(standard input)-02-15 23:13:18.957  3638  3638 E Cuer    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
(standard input)-02-15 23:13:18.982  1619  3862 I ActivityManager: dumpStackTraces pids=null nativepids=null
(standard input)-02-15 23:13:18.988  1619  3862 I ActivityManager: Dumping to /data/anr/anr_2021-02-15-23-13-18-986
(standard input)-02-15 23:13:18.988  1619  3862 I ActivityManager: Collecting stacks for pid 3638
(standard input)-02-15 23:13:18.991  1619  3862 I system_server: libdebuggerd_client: started dumping process 3638
(standard input)-02-15 23:13:18.997   957   957 I Zygote  : Process 26386 exited due to signal 9 (Killed)

**Comment by sentinelweb** [comment]
: FATAL Global Exception
 java.lang.RuntimeException: Unable to create service uk.co.sentinelweb.cuer.app.service.cast.YoutubeCastService: java.lang.IllegalArgumentException: No media session ID allocated
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4198)
       at android.app.ActivityThread.access$1500(ActivityThread.java:237)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
 	at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
 Caused by: java.lang.IllegalArgumentException: No media session ID allocated
	at uk.co.sentinelweb.cuer.app.service.cast.notification.player.PlayerControlsNotificationMedia.buildNotification(PlayerControlsNotificationMedia.kt:76)
 	at uk.co.sentinelweb.cuer.app.service.cast.notification.player.PlayerControlsNotificationMedia.showNotification(PlayerControlsNotificationMedia.kt:40)
	at uk.co.sentinelweb.cuer.app.service.cast.notification.player.PlayerControlsNotification.updateNotification(PlayerControlsNotification.kt:85)
 	at uk.co.sentinelweb.cuer.app.service.cast.notification.player.PlayerControlsNotification.setPlayerState(PlayerControlsNotification.kt:68)
 	at uk.co.sentinelweb.cuer.app.util.cast.listener.YouTubePlayerListener.setupPlayer(YouTubePlayerListener.kt:262)
	at uk.co.sentinelweb.cuer.app.util.cast.listener.YouTubePlayerListener.setPlayerUi(YouTubePlayerListener.kt:47)
 	at uk.co.sentinelweb.cuer.app.util.cast.listener.YoutubeCastConnectionListener.setPlayerUi(YoutubeCastConnectionListener.kt:51)
 	at uk.co.sentinelweb.cuer.app.util.cast.listener.ChromecastYouTubePlayerContextHolder.setPlayerUi(ChromecastYouTubePlayerContextHolder.kt:20)
at uk.co.sentinelweb.cuer.app.service.cast.YoutubeCastServiceController.initialise(YoutubeCastServiceController.kt:21)
	at uk.co.sentinelweb.cuer.app.service.cast.YoutubeCastService.onCreate(YoutubeCastService.kt:34)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:4186)
... 8 more

**Comment by sentinelweb** [comment]
(standard input)-02-17 07:18:47.416  1608  1682 D CompatibilityChangeReporter: Compat change id reported: 136274596; UID 10305; state: DISABLED
(standard input)-02-17 07:18:47.461 12270 12295 V FA      : onActivityCreated
(standard input)-02-17 07:18:47.490 12270 12270 W nelweb.cuer.ap: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
(standard input)-02-17 07:18:47.491 12270 12270 W nelweb.cuer.ap: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
(standard input)-02-17 07:18:47.537  2610  2862 I chatty  : uid=10016(com.google.android.gms) Binder:2610_5 expire 8 lines
(standard input)-02-17 07:18:47.599 12270 12270 D MainPresenter: onPlayServicesOk()
(standard input)-02-17 07:18:47.617  1000  1138 D VSC     : @ 86364.178: [WO] isFlat() nearest_rotation: 4, flat_angle: 65
(standard input)-02-17 07:18:47.617  1000  1138 D VSC     : @ 86364.178: [WO] orientation angle 357, orientation 4
(standard input)-02-17 07:18:47.837  3872  3889 I ogle.android.a: Background young concurrent copying GC freed 360258(20MB) AllocSpace objects, 124(2436KB) LOS objects, 84% free, 4425KB/27MB, paused 261us total 122.571ms
(standard input)-02-17 07:18:47.837  3872  3889 W ogle.android.a: Reducing the number of considered missed Gc histogram windows from 2844 to 100
(standard input)-02-17 07:18:47.854  3872  3891 W System  : A resource failed to call close. 
(standard input)-02-17 07:18:47.907   678   678 E Layer   : [Surface(name=Task=1)/@0x7c5755b - animation-leash#0] No local sync point found
(standard input)-02-17 07:18:47.907   678   678 I chatty  : uid=1000(system) /system/bin/surfaceflinger identical 2 lines
(standard input)-02-17 07:18:47.907   678   678 E Layer   : [Surface(name=Task=1)/@0x7c5755b - animation-leash#0] No local sync point found
(standard input)-02-17 07:18:47.907   678   678 E Layer   : [Surface(name=Task=15606)/@0x66c4b89 - animation-leash#0] No local sync point found
(standard input)-02-17 07:18:47.907   678   678 E Layer   : [Surface(name=Task=15606)/@0x66c4b89 - animation-leash#0] No local sync point found
(standard input)-02-17 07:18:47.959 12270 12270 D MainPresenter: onStart()
(standard input)-02-17 07:18:47.960  1608  3975 W ActivityManager: Bringing down service while still waiting for start foreground: ServiceRecord{bfb80b0 u0 uk.co.sentinelweb.cuer.app/.service.cast.YoutubeCastService}
(standard input)-02-17 07:18:47.966 12270 12270 D MainActivity: checkForPendingNavigation:null > null
(standard input)-02-17 07:18:47.970 12270 12306 V FA      : Activity resumed, time: 86362168
(standard input)-02-17 07:18:47.980 12270 12306 I FA      : Tag Manager is not found and thus will not be used
(standard input)-02-17 07:18:47.990 12270 12270 D YoutubeCastService: Service destroyed
(standard input)-02-17 07:18:47.996 12270 12270 D AndroidRuntime: Shutting down VM
(standard input):02-17 07:18:47.997 12270 12270 E AndroidRuntime: FATAL EXCEPTION: main
(standard input)-02-17 07:18:47.997 12270 12270 E AndroidRuntime: Process: uk.co.sentinelweb.cuer.app, PID: 12270
(standard input)-02-17 07:18:47.997 12270 12270 E AndroidRuntime: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{bfb80b0 u0 uk.co.sentinelweb.cuer.app/.service.cast.YoutubeCastService}
(standard input)-02-17 07:18:47.997 12270 12270 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
(standard input)-02-17 07:18:47.997 12270 12270 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
(standard input)-02-17 07:18:47.997 12270 12270 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
(standard input)-02-17 07:18:47.997 12270 12270 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
(standard input)-02-17 07:18:47.997 12270 12270 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
(standard input)-02-17 07:18:47.997 12270 12270 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
(standard input)-02-17 07:18:47.997 12270 12270 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
--
(standard input)-02-17 07:18:47.997 12270 12270 E AndroidRuntime: Process: uk.co.sentinelweb.cuer.app, PID: 12270
(standard input)-02-17 07:18:47.997 12270 12270 E AndroidRuntime: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{bfb80b0 u0 uk.co.sentinelweb.cuer.app/.service.cast.YoutubeCastService}
(standard input)-02-17 07:18:47.997 12270 12270 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
(standard input)-02-17 07:18:47.997 12270 12270 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
(standard input)-02-17 07:18:47.997 12270 12270 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
(standard input)-02-17 07:18:47.997 12270 12270 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
(standard input)-02-17 07:18:47.997 12270 12270 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
(standard input)-02-17 07:18:47.997 12270 12270 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
(standard input)-02-17 07:18:47.997 12270 12270 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
(standard input):02-17 07:18:47.998 12270 12270 E Cuer    : FATAL Global Exception
(standard input)-02-17 07:18:47.998 12270 12270 E Cuer    : android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{bfb80b0 u0 uk.co.sentinelweb.cuer.app/.service.cast.YoutubeCastService}
(standard input)-02-17 07:18:47.998 12270 12270 E Cuer    : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
(standard input)-02-17 07:18:47.998 12270 12270 E Cuer    : 	at android.os.Handler.dispatchMessage(Handler.java:106)
(standard input)-02-17 07:18:47.998 12270 12270 E Cuer    : 	at android.os.Looper.loop(Looper.java:223)
(standard input)-02-17 07:18:47.998 12270 12270 E Cuer    : 	at android.app.ActivityThread.main(ActivityThread.java:7660)
(standard input)-02-17 07:18:47.998 12270 12270 E Cuer    : 	at java.lang.reflect.Method.invoke(Native Method)
(standard input)-02-17 07:18:47.998 12270 12270 E Cuer    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
(standard input)-02-17 07:18:47.998 12270 12270 E Cuer    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
(standard input)-02-17 07:18:48.041  2610  8608 I chatty  : uid=10016 com.google.android.gms.persistent expire 1 line
(standard input)-02-17 07:18:48.170 12270 12301 D TransportRuntime.SQLiteEventStore: Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
(standard input)-02-17 07:18:48.177 12270 12301 D TransportRuntime.JobInfoScheduler: Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=498873348 in 28795ms(Backend next call timestamp 1613542756971). Attempt 1
(standard input)-02-17 07:18:48.185 12270 12306 V FA      : Recording user engagement, ms: 216
(standard input)-02-17 07:18:48.193  1608 12341 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
(standard input)-02-17 07:18:48.194  1608  4025 W ActivityTaskManager:   Force finishing activity uk.co.sentinelweb.cuer.app/.ui.main.MainActivity
(standard input)-02-17 07:18:48.217  3008 12321 V FA-SVC  : Background event processing time, ms: 32
(standard input)-02-17 07:18:48.217  1608  3975 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
(standard input)-02-17 07:18:48.220  1608  1696 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
(standard input)-02-17 07:18:48.223  3008 12321 V FA-SVC  : Logging event: origin=auto,name=user_engagement(_e),params=Bundle[{ga_event_origin(_o)=auto, engagement_time_msec(_et)=216, _fr=1, ga_screen_class(_sc)=MainActivity, ga_screen_id(_si)=-9083450124015012823}]

**Comment by sentinelweb** [comment]
`(standard input)-02-17 07:18:42.376  5606  5606 D CastPlayerPresenter: playState = PLAYING
(standard input)-02-17 07:18:42.382  5606  5606 D MainActivity: checkForPendingNavigation:null > null
(standard input)-02-17 07:18:42.385  5606  5606 D MainActivity: checkForPendingNavigation:PLAYLIST_FRAGMENT > null
(standard input)-02-17 07:18:42.385  5606 12210 V FA      : Activity resumed, time: 86356584
(standard input)-02-17 07:18:42.386  5606  5606 D PlaylistFragment: onResume: got arguments pl=12, item=0, src=LOCAL
(standard input)-02-17 07:18:42.387  5606  5606 D PlaylistFragment: onResume: apply nav args model = NavigationModel(target=PLAYLIST_FRAGMENT, params={PLAYLIST_ID=12, PLAY_NOW=false, SOURCE=LOCAL})
(standard input)-02-17 07:18:42.387  5606  5606 D Cuer    : clearPendingNavigation:PLAYLIST_FRAGMENT > null
(standard input)-02-17 07:18:42.393  5606 12210 V FA      : Connection attempt already in progress
(standard input)-02-17 07:18:42.397  5606  5606 D YoutubeCastService: Service destroyed
(standard input)-02-17 07:18:42.398  5606 12210 V FA      : Screen exposed for less than 1000 ms. Event not sent. time: 11
(standard input)-02-17 07:18:42.399  5606 12210 V FA      : Connection attempt already in progress
(standard input)-02-17 07:18:42.399  5606 12210 V FA      : Activity paused, time: 86356596
(standard input)-02-17 07:18:42.404  5606  5606 I Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
(standard input)-02-17 07:18:42.428  1608  1897 D ConnectivityService: NetReassign [no changes]
(standard input)-02-17 07:18:42.494  5606  5606 D MainPresenter: onStop()
(standard input)-02-17 07:18:42.521  1991  1991 W Choreographer: Frame time is 0.152924 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
(standard input)-02-17 07:18:42.529  5606 12209 V FA      : onActivityCreated
(standard input)-02-17 07:18:42.533  5606  5606 D PlaylistsFragment: 51753759 - init
(standard input)-02-17 07:18:42.541  5606  5606 D PlaylistsFragment: 51753759 - onCreate
(standard input)-02-17 07:18:42.563  5606  5606 D MainPresenter: onPlayServicesOk()
(standard input)-02-17 07:18:42.687  1608  1695 I chatty  : uid=1000(system) android.bg expire 1 line
(standard input)-02-17 07:18:42.721  5606  5606 D MainPresenter: onStart()
(standard input)-02-17 07:18:42.724  5606  5606 D CastPlayerPresenter: playState = PLAYING
(standard input)-02-17 07:18:42.730  5606  5606 D MainActivity: checkForPendingNavigation:null > null
(standard input)-02-17 07:18:42.732  5606 12210 V FA      : Activity resumed, time: 86356931
(standard input)-02-17 07:18:42.733  5606  5606 D MainActivity: checkForPendingNavigation:PLAYLIST_FRAGMENT > null
(standard input)-02-17 07:18:42.733  5606  5606 D PlaylistFragment: onResume: got arguments pl=-1, item=0, src=null
(standard input)-02-17 07:18:42.733  5606  5606 D PlaylistFragment: onResume: got no nav args
(standard input)-02-17 07:18:42.737  5606 12210 V FA      : Connection attempt already in progress
(standard input)-02-17 07:18:42.822  5606  5606 D AndroidRuntime: Shutting down VM
(standard input):02-17 07:18:42.822  5606  5606 E AndroidRuntime: FATAL EXCEPTION: main
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: Process: uk.co.sentinelweb.cuer.app, PID: 5606
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: java.lang.IllegalStateException: FragmentManager has been destroyed
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1795)
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1855)
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
--
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: Process: uk.co.sentinelweb.cuer.app, PID: 5606
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: java.lang.IllegalStateException: FragmentManager has been destroyed
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1795)
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1855)
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
(standard input)-02-17 07:18:42.822  5606  5606 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
(standard input):02-17 07:18:42.823  5606  5606 E Cuer    : FATAL Global Exception
(standard input)-02-17 07:18:42.823  5606  5606 E Cuer    : java.lang.IllegalStateException: FragmentManager has been destroyed
(standard input)-02-17 07:18:42.823  5606  5606 E Cuer    : 	at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1795)
(standard input)-02-17 07:18:42.823  5606  5606 E Cuer    : 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1855)
(standard input)-02-17 07:18:42.823  5606  5606 E Cuer    : 	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
(standard input)-02-17 07:18:42.823  5606  5606 E Cuer    : 	at android.os.Handler.handleCallback(Handler.java:938)
(standard input)-02-17 07:18:42.823  5606  5606 E Cuer    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
(standard input)-02-17 07:18:42.823  5606  5606 E Cuer    : 	at android.os.Looper.loop(Looper.java:223)
(standard input)-02-17 07:18:42.823  5606  5606 E Cuer    : 	at android.app.ActivityThread.main(ActivityThread.java:7660)
(standard input)-02-17 07:18:42.823  5606  5606 E Cuer    : 	at java.lang.reflect.Method.invoke(Native Method)
(standard input)-02-17 07:18:42.823  5606  5606 E Cuer    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
(standard input)-02-17 07:18:42.823  5606  5606 E Cuer    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
(standard input)-02-17 07:18:43.009  5606 12210 V FA      : Connection attempt already in progress
(standard input)-02-17 07:18:43.011  5606 12210 V FA      : Recording user engagement, ms: 278
(standard input)-02-17 07:18:43.032 12109 12179 E ActivityThread: Failed to find provider info for com.google.android.googlequicksearchbox.GsaPublicContentProvider
(standard input)-02-17 07:18:43.033 12109 12179 W AssistantConfig: appIntegrationDataInBase64 is null
(standard input)-02-17 07:18:43.044  5606 12210 V FA      : Connection attempt already in progress
(standard input)-02-17 07:18:43.045  5606  5678 D TransportRuntime.SQLiteEventStore: Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
(standard input)-02-17 07:18:43.056  5606  5678 D TransportRuntime.JobInfoScheduler: Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=498873348 in 1000ms(Backend next call timestamp 1613462847026). Attempt 1
(standard input)-02-17 07:18:43.058 12109 12168 D CompatibilityChangeReporter: Compat change id reported: 147600208; UID 10132; state: ENABLED
(standard input)-02-17 07:18:43.065 12109 12205 D TelephonyRegistryManager: onSubscriptionsChangedListener callback received.
(standard input)-02-17 07:18:43.072  1608 12229 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
(standard input)-02-17 07:18:43.073  1608  3964 W ActivityTaskManager:   Force finishing activity uk.co.sentinelweb.cuer.app/.ui.main.MainActivity
(standard input)-02-17 07:18:43.075 12109 12168 I BugleRcsEngine: [5516] ahuo.<init>: (Sim): Initializing SimStateTracker with multi-sim support
(standard input)-02-17 07:18:43.076 12109 12168 I BugleRcsEngine: [5516] ahuv.<init>: (SingleSim): Initializing SimStateTracker for single-sim device
(standard input)-02-17 07:18:43.076 12109 12168 I BugleRcsEngine: [5516] agnv.l: Reinitialize CSLib Flags: com.google.android.ims.library
(standard input)-02-17 07:18:43.091 12109 12179 W Bugle   : BuglePhoneNumberUtils: canonicalizeMccMnc: invalid mccmnc. mcc: null, mnc: null
(standard input)-02-17 07:18:43.100  1608  1696 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
(standard input)-02-17 07:18:43.100  1608  1696 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
(standard input)-02-17 07:18:43.104  5606  5606 I Process : Sending signal. PID: 5606 SIG: 9
(standard input)-02-17 07:18:43.105 12109 12168 I BugleRcsEngine: [5516] agnv.l: Reinitialize CSLib Flags: com.google.android.ims.library
(standard input)-02-17 07:18:43.107 12109 12205 D TelephonyRegistryManager: onSubscriptionsChangedListener callback received.
(standard input)-02-17 07:18:43.112 12109 12230 I BugleRcsEngine: [5542] ahus.c: do not delay first event
(standard input)-02-17 07:18:43.114 12109 12233 W BugleRcsEngine: [5545] ahuo.fl: (Sim): Unexpected action: android.intent.action.ACTION_DEFAULT_VOICE_SUBSCRIPTION_CHANGED
(standard input)-02-17 07:18:43.116 12109 12232 W BugleRcsEngine: [5544] ahuo.fl: (Sim): Unexpected action: android.intent.action.ACTION_DEFAULT_DATA_SUBSCRIPTION_CHANGED
(standard input)-02-17 07:18:43.131 12109 12168 W Bugle   : BuglePhoneNumberUtils: canonicalizeMccMnc: invalid mccmnc. mcc: null, mnc: null
(standard input)-02-17 07:18:43.135 12109 12230 I BugleRcsEngine: [5542] ahuo.fk: (Sim): Processing an intent
(standard input)-02-17 07:18:43.135 12109 12231 I BugleRcsEngine: [5543] ahus.c: SIM delay is not enabled
(standard input)-02-17 07:18:43.135 12109 12231 W BugleRcsEngine: [5543] ahuo.a: (Sim): process intent: android.intent.action.SIM_STATE_CHANGED
(standard input)-02-17 07:18:43.135 12109 12230 I BugleRcsEngine: [5542] ahuo.s: (Sim): SIM state LOADED
(standard input)-02-17 07:18:43.150 12109 12182 I RcsClientLib: Connecting SignupService
(standard input)-02-17 07:18:43.152 12109 12182 I RcsClientLib: shouldUseCarrierServicesJibeService: true, CarrierServices rcs service found: true
(standard input)-02-17 07:18:43.152 12109 12182 I RcsClientLib: Binding to JibeService in CarrierServices.
(standard input)-02-17 07:18:43.156 12109 12109 I RcsClientLib: com.google.android.rcs.client.signup.SignupService connected
(standard input)-02-17 07:18:43.157 12109 12230 I BugleRcsEngine: [5542] ahuo.s: (Sim): SIM changed: false. current id: redacted-pii:sim_id[19-chars]; stored id: redacted-pii:sim_id[19-chars]; isFiDevice: false; subId: 1; slotIndex: 0
(standard input)-02-17 07:18:43.159  2787  2872 I CarrierServices: [130] cao.a: RcsAvailabilityManager: Calculating Rcs Availability
(standard input)-02-17 07:18:43.163  2787 30868 I CarrierServices: [528] cnf.V: Received Provisioning Event: [Bugle information (100)]
(standard input)-02-17 07:18:43.163  2787 30868 I CarrierServices: [528] cnf.V: JibeService is running, passing event to provisioning engine.
(standard input)-02-17 07:18:43.163  2787 30868 I CarrierServices: [528] cae.k: Handling Provisioning Event: [Bugle information (100)]
(standard input)-02-17 07:18:43.164  2787  2872 I CarrierServices: [130] cck.b: Bugle is default SMS app: true
(standard input)-02-17 07:18:43.165  2787 30868 I CarrierServices: [528] cao.a: RcsAvailabilityManager: Calculating Rcs Availability`

**Comment by sentinelweb** [comment]
https://stackoverflow.com/questions/60641206/java-lang-illegalstateexception-fragmentmanager-has-been-destroyed
