### ISSUE TITLE
crash from viewmodel when changing light/dark theme

### ISSUE THREAD

**Issue by sentinelweb** [sentinelweb/cuer#146]
1. go to select playlist - add playlist
2. switch light to dark theme
3. crash below

The state object should be preserved with the viewModel - check the instance numbers for the state before and after swing the theme

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: uk.co.sentinelweb.cuer.app, PID: 2672
    kotlin.UninitializedPropertyAccessException: lateinit property playlist has not been initialized
        at uk.co.sentinelweb.cuer.app.ui.playlist_edit.PlaylistEditContract$State.getPlaylist(PlaylistEditContract.kt:28)
        at uk.co.sentinelweb.cuer.app.ui.playlist_edit.PlaylistEditViewModel.onTitleChanged(PlaylistEditViewModel.kt:84)
        at uk.co.sentinelweb.cuer.app.ui.playlist_edit.PlaylistEditFragment$onViewCreated$$inlined$doAfterTextChanged$1.afterTextChanged(TextView.kt:98)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:10551)`

**Comment by sentinelweb** [comment]
FATAL EXCEPTION: main
 Process: uk.co.sentinelweb.cuer.app, PID: 13535
 java.lang.IllegalStateException: Scan fragment not visible
 	at uk.co.sentinelweb.cuer.app.ui.share.ShareActivity.checkIntent(ShareActivity.kt:22)
 	at uk.co.sentinelweb.cuer.app.ui.share.ShareActivity.onStart(ShareActivity.kt:2)
 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
 	at android.app.Activity.performStart(Activity.java:7825)
 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
 	at android.os.Handler.dispatchMessage(Handler.java:107)
 	at android.os.Looper.loop(Looper.java:214)
 	at android.app.ActivityThread.main(ActivityThread.java:7356)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by sentinelweb** [comment]
fixed in #245
