### ISSUE TITLE
local player bugs

### ISSUE THREAD

**Issue by sentinelweb** [sentinelweb/cuer#199]
- [x] fix skip on live before videos loads goes back 12 hrs - disable skip before load complete
- [x] position isn't restored for when switching portrait <-> land when playlist is "play from start" - try to share the player view
- [x] cleanup media session on exit
- [x] PLAY BUTTON ON VIEW ITEM EDIT SHOULD PLAY LOCAL IF NOT CONNECTED TO CAST
- [x] review behaviour of all play buttons (put icon on image and make that play - then description row opens detail)
- [x] floating window player
- [x] check touchinterceptor from MyPod video player to stop focus problem on fullscreen player
- [ ] preferred player setting (port/full/float)
- [ ] pref to auto open floating player when exit player
- [ ] play from search (auto add to default)
- [x] control floating player from main player
- [x] make playerlistener binding work - need a singleton PlayerContract.PlayerControls.Listener that can work for all players. still not bound for portrait player
- [x] ripple on compact player buttons
- [x] play/pause on mian deoisnt work with floating
- [x] update floating skip time on main change

**Comment by sentinelweb** [comment]
```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[Dispatchers.Unconfined, Continuation at kotlinx.coroutines.channels.TickerChannelsKt.fixedPeriodTicker(TickerChannels.kt:88)@47343e]){Completed}@630529f. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
10-31 08:15:58.240 27181 27892 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
10-31 08:15:58.240 27181 27892 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:251)
10-31 08:15:58.240 27181 27892 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
10-31 08:15:58.240 27181 27892 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:398)
10-31 08:15:58.240 27181 27892 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:432)
10-31 08:15:58.240 27181 27892 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:421)
10-31 08:15:58.240 27181 27892 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:519)
10-31 08:15:58.240 27181 27892 E AndroidRuntime: 	at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.run(EventLoop.common.kt:489)
10-31 08:15:58.240 27181 27892 E AndroidRuntime: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
10-31 08:15:58.240 27181 27892 E AndroidRuntime: 	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
10-31 08:15:58.240 27181 27892 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
10-31 08:15:58.240 27181 27892 E AndroidRuntime: Caused by: java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.internal.DispatchedContinuation
10-31 08:15:58.240 27181 27892 E AndroidRuntime: 	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:108)
10-31 08:15:58.240 27181 27892 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
10-31 08:15:58.240 27181 27892 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
10-31 08:15:58.240 27181 27892 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
10-31 08:15:58.240 27181 27892 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
10-31 08:15:58.240 27181 27892 E AndroidRuntime: 	... 9 more
```
