### ISSUE TITLE
make content catgalgoue

### ISSUE THREAD

**Issue by sentinelweb** [sentinelweb/cuer#200]
- [ ] language and tag based links to playlists/channels/videos
- [ ] firebase datastore (could just embed JS file for first version)
- [ ] web ui to configure / add items to catalogue
- [ ] may need to convert net api to ktor for use in js
- [ ] 

tutorials
- [ ] https://signal.h2g.io/firebase-with-kotlin-introduction-part-1-of-2-39541a3fa87b
- [ ] https://signal.h2g.io/firebase-cloud-functions-with-kotlin-firebase-cloud-functions-part-2-of-2-e0d5c1d6b217
- [ ] https://kanawish.com/posts/201020-kotlin-js/
- [ ] https://kanawish.com/posts/210328-kjs-coroutines-and-firebase/
- [ ] look at https://github.com/GitLiveApp/firebase-kotlin-sdk
- [ ] firebase web codelab https://firebase.google.com/codelabs/firestore-web#0

**Comment by sentinelweb** [comment]
11-21 15:56:20.048  1315  1413 E AndroidRuntime: FATAL EXCEPTION: pool-19-thread-2
11-21 15:56:20.048  1315  1413 E AndroidRuntime: Process: uk.co.sentinelweb.cuer.app, PID: 1315
11-21 15:56:20.048  1315  1413 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=14; index=-1
11-21 15:56:20.048  1315  1413 E AndroidRuntime: 	at java.util.ArrayList.set(ArrayList.java:455)
11-21 15:56:20.048  1315  1413 E AndroidRuntime: 	at uk.co.sentinelweb.cuer.app.queue.QueueMediator.updateCurrentItemFromMedia(QueueMediator.kt:43)
11-21 15:56:20.048  1315  1413 E AndroidRuntime: 	at uk.co.sentinelweb.cuer.app.queue.QueueMediator$updateCurrentItemFromMedia$1.invokeSuspend(QueueMediator.kt:1)
11-21 15:56:20.048  1315  1413 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
11-21 15:56:20.048  1315  1413 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
11-21 15:56:20.048  1315  1413 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-21 15:56:20.048  1315  1413 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-21 15:56:20.048  1315  1413 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)

**Comment by sentinelweb** [comment]
11-21 15:56:19.730  1315  1315 D PlaylistPresenter: q.playlist change id=121 index=0
11-21 15:56:19.878  1315  1315 W System.err: java.lang.NumberFormatException: empty String
11-21 15:56:19.879  1315  1315 W System.err: 	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
11-21 15:56:19.879  1315  1315 W System.err: 	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
11-21 15:56:19.879  1315  1315 W System.err: 	at java.lang.Float.parseFloat(Float.java:451)
11-21 15:56:19.879  1315  1315 W System.err: 	at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.YouTubePlayerBridge.sendVideoCurrentTime(YouTubePlayerBridge.kt:1)
11-21 15:56:19.879  1315  1315 W System.err: 	at com.pierfrancescosoffritti.androidyoutubeplayer.chromecast.chromecastsender.io.youtube.ChromecastYouTubeMessageDispatcher.onMessageReceived(ChromecastYouTubeMessageDispatcher.kt:15)
11-21 15:56:19.879  1315  1315 W System.err: 	at com.pierfrancescosoffritti.androidyoutubeplayer.chromecast.chromecastsender.io.youtube.ChromecastYouTubeIOChannel.onMessageReceived(ChromecastYouTubeIOChannel.kt:10)
11-21 15:56:19.879  1315  1315 W System.err: 	at com.google.android.gms.internal.cast.zzdj.run(Unknown Source:10)
11-21 15:56:19.879  1315  1315 W System.err: 	at android.os.Handler.handleCallback(Handler.java:938)
11-21 15:56:19.879  1315  1315 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-21 15:56:19.879  1315  1315 W System.err: 	at com.google.android.gms.internal.cast.zzez.dispatchMessage(Unknown Source:1)
11-21 15:56:19.879  1315  1315 W System.err: 	at android.os.Looper.loopOnce(Looper.java:201)
11-21 15:56:19.879  1315  1315 W System.err: 	at android.os.Looper.loop(Looper.java:288)
11-21 15:56:19.879  1315  1315 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7838)
11-21 15:56:19.879  1315  1315 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
11-21 15:56:19.879  1315  1315 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-21 15:56:19.879  1315  1315 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
11-21 15:56:19.880  1315  1315 W System.err: java.lang.NumberFormatException: empty String

**Comment by sentinelweb** [comment]
- https://www.youtube.com/user/chomskysphilosophy/videos
