### ISSUE TITLE
player issues

### ISSUE THREAD

**Issue by sentinelweb** [sentinelweb/cuer#246]
- [x] should show current queue item/playlist/title in main player on load
- [x] pressing compact play button should do something (choose cast/localplayer/float?)
- [x] raise / lower the player on scroll up/down - for more list space
- [ ] activity transition to player?
- [ ] crop bitmap squar in play notif
- [x] set floating notif icon
- [x] check play postion check isn't too close to end at start - just goes strain to the next video - should be 10 s maybe try 30s 
- [x] put play-yang in loading spinner
- [x] test getting permission for floating player
- [x] stop seekbar jumping on player after touch up
- [x] make a play use case - revise button actions for playlist fab / item fab / play but
    - [x] probably they should all have the same logic
    - [x] dialog choose cast/localplayer/float? 
    - [x] ~~and remember selection?~~
    - [x] add launch youtube option
    - [x] ~~add play from start checkbox? sticky~~
    - [x] remove context options

**Comment by sentinelweb** [comment]
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
11-19 10:28:58.034  9935  9935 E AndroidRuntime: 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5247)
11-19 10:28:58.034  9935  9935 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:5076)
11-19 10:28:58.034  9935  9935 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:5048)
11-19 10:28:58.034  9935  9935 E AndroidRuntime: 	at uk.co.sentinelweb.cuer.app.ui.ytplayer.AytViewHolder.addView(AytViewHolder.kt:51)
11-19 10:28:58.034  9935  9935 E AndroidRuntime: 	at uk.co.sentinelweb.cuer.app.ui.ytplayer.ayt_portrait.AytPortraitActivity$MviViewImpl.<init>(AytPortraitActivity.kt:139)
11-19 10:28:58.034  9935  9935 E AndroidRuntime: 	at uk.co.sentinelweb.cuer.app.ui.ytplayer.ayt_portrait.AytPortraitActivity.onPostCreate(AytPortraitActivity.kt:101)
11-19 10:28:58.034  9935  9935 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1403)
11-19 10:28:58.034  9935  9935 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3687)
11-19 10:28:58.034  9935  9935 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
11-19 10:28:58.034  9935  9935 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
11-19 10:28:58.034  9935  9935 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
11-19 10:28:58.034  9935  9935 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
11-19 10:28:58.034  9935  9935 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
11-19 10:28:58.034  9935  9935 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-19 10:28:58.034  9935  9935 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
11-19 10:28:58.034  9935  9935 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
11-19 10:28:58.034  9935  9935 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7838)
11-19 10:28:58.034  9935  9935 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-19 10:28:58.034  9935  9935 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-19 10:28:58.034  9935  9935 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
