### ISSUE TITLE
misc issues

### ISSUE THREAD

**Issue by sentinelweb** [sentinelweb/cuer#253]
Share
- [x] hide playlist/item play fab on share screen
- [x] mark watched on playlist edit with memory playlist crashes

Player
- [x] show player on browse screen (extend space at bottom for browse)
- [x] player stays lowered on PlaylistItemEdit screen if cant scroll

Playlist
- [x] removing a playList in PlaylistItemEdit doesnt save
- [ ] ~~moving item to a sibling playlist says item already on this playlist~~
- [x] when creating a playlist - parent selection didnt save

Navigation
- [x] getting "no apps can perform this action" after clicking a link on description and going back
- [x] playlist reload every time bottom nav pressed
- [x] doesn't remember playlist last tab
- [x] bottom nav doesnt indicate browse at start
- [x] fragment goes back to browse when change day/night mode
- [x] channel doesnt launch in playlistitemedit

Dialog
- [x]  show a warning on support crypto - esp for eth - dialog shows copied address in header and description below so the user can check the address use `SpannaleStringBuilderKt` `backgroundColor`,`bold`, `color`, `italic`, `scale`, `strikeThrough`, `superscript`, `underline`

**Comment by sentinelweb** [comment]
kotlin.UninitializedPropertyAccessException: lateinit property source has not been initialized
11-25 16:59:38.397  5815  5815 E Cuer    : 	at uk.co.sentinelweb.cuer.app.ui.playlist_item_edit.PlaylistItemEditContract$State.getSource(PlaylistItemEditContract.kt:1)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at uk.co.sentinelweb.cuer.app.ui.playlist_item_edit.PlaylistItemEditContract$State$$serializer.serialize(PlaylistItemEditContract.kt:10)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:17)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at kotlinx.serialization.json.Json.encodeToString(Json.kt:6)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at uk.co.sentinelweb.cuer.app.ui.playlist_item_edit.PlaylistItemEditFragment.onSaveInstanceState(PlaylistItemEditFragment.kt:4)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at androidx.fragment.app.FragmentManager.saveAllState(FragmentManager.java:19)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at androidx.fragment.app.FragmentManager.saveAllState(FragmentManager.java:21)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at androidx.fragment.app.FragmentActivity$1.saveState(FragmentActivity.java:6)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.java:8)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:7)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at android.app.Activity.performSaveInstanceState(Activity.java:2198)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1508)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5756)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5161)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5127)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5192)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at android.os.Looper.loopOnce(Looper.java:201)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at android.os.Looper.loop(Looper.java:288)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at android.app.ActivityThread.main(ActivityThread.java:7838)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at java.lang.reflect.Method.invoke(Native Method)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-25 16:59:38.397  5815  5815 E Cuer    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by sentinelweb** [comment]
FATAL Global Exception
11-27 13:34:40.597  6941  6941 E Cuer    : java.lang.IllegalStateException: can't get Scope for PlaylistFragment{941287e} (f0193689-8804-4dce-8411-28f1465d7d3a)
11-27 13:34:40.597  6941  6941 E Cuer    : 	at org.koin.androidx.scope.LifecycleScopeDelegate.getValue(LifecycleScopeDelegate.kt:2)
11-27 13:34:40.597  6941  6941 E Cuer    : 	at uk.co.sentinelweb.cuer.app.ui.playlist.PlaylistFragment.getScope(PlaylistFragment.kt:1)
11-27 13:34:40.597  6941  6941 E Cuer    : 	at org.koin.android.ext.android.ComponentCallbackExtKt.getDefaultScope(ComponentCallbackExt.kt:1)
11-27 13:34:40.597  6941  6941 E Cuer    : 	at uk.co.sentinelweb.cuer.app.ui.playlist.PlaylistFragment$special$$inlined$inject$default$3.invoke(ComponentCallbackExt.kt:2)
11-27 13:34:40.597  6941  6941 E Cuer    : 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:5)
11-27 13:34:40.597  6941  6941 E Cuer    : 	at uk.co.sentinelweb.cuer.app.ui.playlist.PlaylistFragment.showUndo(PlaylistFragment.kt:1)
11-27 13:34:40.597  6941  6941 E Cuer    : 	at uk.co.sentinelweb.cuer.app.ui.playlist.PlaylistPresenter$onItemSwipeLeft$1.invokeSuspend(PlaylistPresenter.kt:22)
11-27 13:34:40.597  6941  6941 E Cuer    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
11-27 13:34:40.597  6941  6941 E Cuer    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
11-27 13:34:40.597  6941  6941 E Cuer    : 	at android.os.Handler.handleCallback(Handler.java:938)
11-27 13:34:40.597  6941  6941 E Cuer    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-27 13:34:40.597  6941  6941 E Cuer    : 	at android.os.Looper.loopOnce(Looper.java:201)
11-27 13:34:40.597  6941  6941 E Cuer    : 	at android.os.Looper.loop(Looper.java:288)
11-27 13:34:40.597  6941  6941 E Cuer    : 	at android.app.ActivityThread.main(ActivityThread.java:7838)
11-27 13:34:40.597  6941  6941 E Cuer    : 	at java.lang.reflect.Method.invoke(Native Method)
11-27 13:34:40.597  6941  6941 E Cuer    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-27 13:34:40.597  6941  6941 E Cuer    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
