### ISSUE TITLE
Make an auto backup prompt

### ISSUE THREAD

**Issue by sentinelweb** [sentinelweb/cuer#317]
- [x] Should show every day (maybe a notification?) 
- [x] save to the same file each day (per device) e.g. cuer-backup-current-pixel.json 
- [x] try to remember the save location URL and just save it automatically
- [x] ability to select an existing backup file to restore data
- [x] handle exception
- [ ] extract strings
- [x] delete restore file after import
- [x] handle no content provider exception: might just be dropbox? not sure - happens after restart

**Comment by sentinelweb** [comment]
handle
java.lang.SecurityException: Permission Denial: opening provider com.dropbox.product.android.dbapp.document_provider.DropboxDocumentProvider from ProcessRecord{5265499 6989:uk.co.sentinelweb.cuer.app.debug/u0a272} (pid=6989, uid=10272) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
        at android.os.Parcel.createException(Parcel.java:2995)
        at android.os.Parcel.readException(Parcel.java:2978)
        at android.os.Parcel.readException(Parcel.java:2920)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5224)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:7033)
        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3420)
        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2526)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1844)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:1562)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:1537)
        at uk.co.sentinelweb.cuer.app.util.wrapper.FileWrapper.overwriteFileToUri(FileWrapper.kt:37)
        at uk.co.sentinelweb.cuer.app.ui.settings.PrefBackupPresenter.saveAutoBackup(PrefBackupPresenter.kt:123)
        at uk.co.sentinelweb.cuer.app.ui.settings.PrefBackupPresenter.access$saveAutoBackup(PrefBackupPresenter.kt:19)
        at uk.co.sentinelweb.cuer.app.ui.settings.PrefBackupPresenter$autoBackupDatabaseToJson$1.invokeSuspend(PrefBackupPresenter.kt:53)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@143341d, Dispatchers.Main.immediate]
    Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ContentProviderHelper.checkAssociationAndPermissionLocked(ContentProviderHelper.java:631)
        at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:256)
        at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:136)
        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:6476)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2395)

**Comment by sentinelweb** [comment]
fix this error:
```
2022-10-24 16:21:28.323 13359-13359/uk.co.sentinelweb.cuer.app.debug E/Cuer: FATAL Global Exception
    java.io.FileNotFoundException: No content provider: content://com.dropbox.product.android.dbapp.document_provider.documents/document/L3NhZi8xL2NvbnRlbnQlM0ElMkYlMkZjb20uZHJvcGJveC5hbmRyb2lkLkRyb3Bib3glMkZtZXRh%0AZGF0YSUyRmJhY2t1cHMlMkZDdWVyJTJGdjMtY3VycmVudC1jdWVyLWRlYnVnLWJhY2t1cC1QaXhl%0AbF82LnppcC8lNUI1MSUyQyUyMC0xMTklMkMlMjA5NSUyQyUyMDg4JTJDJTIwLTc0JTJDJTIwMTE5%0AJTJDJTIwLTI5JTJDJTIwLTczJTJDJTIwLTQ1JTJDJTIwLTEyMSUyQyUyMC0xMjUlMkMlMjAtMjEl%0AMkMlMjAtMzUlMkMlMjA2MCUyQyUyMC0xMjIlMkMlMjAzNiUyQyUyMDEyNiUyQyUyMC04OCUyQyUy%0AMC0xMDUlMkMlMjAyNyUyQyUyMDUlMkMlMjAtNDMlMkMlMjAtOTYlMkMlMjAtMTIxJTJDJTIwLTI1%0AJTJDJTIwLTU5JTJDJTIwLTgyJTJDJTIwLTg0JTJDJTIwLTc4JTJDJTIwMTIlMkMlMjAxMTElMkMl%0AMjA2MCU1RA%3D%3D%0A
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1846)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:1562)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:1537)
        at uk.co.sentinelweb.cuer.app.util.wrapper.FileWrapper.overwriteFileToUri(FileWrapper.kt:35)
        at uk.co.sentinelweb.cuer.app.ui.settings.PrefBackupPresenter.saveAutoBackup(PrefBackupPresenter.kt:145)
        at uk.co.sentinelweb.cuer.app.ui.settings.PrefBackupPresenter.access$saveAutoBackup(PrefBackupPresenter.kt:20)
        at uk.co.sentinelweb.cuer.app.ui.settings.PrefBackupPresenter$autoBackupDatabaseToJson$1.invokeSuspend(PrefBackupPresenter.kt:54)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a61609a, Dispatchers.Main.immediate]
```
