### ISSUE TITLE
navinging to a link on the share page closes the share activity on back 

### ISSUE THREAD

**Issue by sentinelweb** [sentinelweb/cuer#321]
share video
click link
back goes back to youtube

- [x]  activity is finishing - possibly related to #279 
    -  the finish on ShareActivity.onUserLeaveHint is doing it 

added ShareNavigationHack injection to bypass onUserLeaveHint hack 

- [x] support link click triggers user leave exit 
- [x] refactor injections to itemedit 
- [ ] install leak canary

**Comment by sentinelweb** [comment]
fix this
```
2022-10-25 09:49:18.511 27801-27801/uk.co.sentinelweb.cuer.app.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: uk.co.sentinelweb.cuer.app.debug, PID: 27801
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 798220 bytes
        at android.app.ActivityClient.activityStopped(ActivityClient.java:88)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: android.os.TransactionTooLargeException: data parcel size 798220 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:584)
        at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1248)
        at android.app.ActivityClient.activityStopped(ActivityClient.java:85)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143) 
        at android.os.Handler.handleCallback(Handler.java:942) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7898) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
2022-10-25 09:49:18.512 27801-27801/uk.co.sentinelweb.cuer.app.debug E/Cuer: FATAL Global Exception
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 798220 bytes
        at android.app.ActivityClient.activityStopped(ActivityClient.java:88)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: android.os.TransactionTooLargeException: data parcel size 798220 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:584)
        at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1248)
        at android.app.ActivityClient.activityStopped(ActivityClient.java:85)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143) 
        at android.os.Handler.handleCallback(Handler.java:942) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7898) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```
