### ISSUE TITLE
Crash when saving playlist item

### ISSUE THREAD

**Issue by sentinelweb** [sentinelweb/cuer#337]
goto starred items wingsuit , unstar, back

seems to be when the item is on multiple playlists - 

possibly when second playliust was added a duplicate meddia item was made?

possibly introduced in #335 
```
2022-10-28 16:50:35.628 10708-10761/uk.co.sentinelweb.cuer.app.debug E/SqldelightPlaylistItemDatabaseRepository: couldn't save playlist item
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: playlist_item.media_id, playlist_item.playlist_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
        at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:730)
        at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:621)
        at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:47)
        at androidx.sqlite.db.framework.FrameworkSQLiteStatement.execute(FrameworkSQLiteStatement.java:41)
        at com.squareup.sqldelight.android.AndroidPreparedStatement.execute(AndroidSqliteDriver.kt:220)
        at com.squareup.sqldelight.android.AndroidSqliteDriver$execute$2.invoke(AndroidSqliteDriver.kt:142)
        at com.squareup.sqldelight.android.AndroidSqliteDriver$execute$2.invoke(AndroidSqliteDriver.kt:142)
        at com.squareup.sqldelight.android.AndroidSqliteDriver.execute(AndroidSqliteDriver.kt:127)
        at com.squareup.sqldelight.android.AndroidSqliteDriver.execute(AndroidSqliteDriver.kt:142)
        at uk.co.sentinelweb.cuer.app.db.database.PlaylistItemEntityQueriesImpl.create(DatabaseImpl.kt:1838)
        at uk.co.sentinelweb.cuer.db.repository.SqldelightPlaylistItemDatabaseRepository$save$2.invokeSuspend(SqldelightPlaylistItemDatabaseRepository.kt:65)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2022-10-28 16:50:35.629 10708-10708/uk.co.sentinelweb.cuer.app.debug E/PlaylistItemEditViewModel: Error saving playlistItem
    uk.co.sentinelweb.cuer.app.orchestrator.OrchestratorContract$DatabaseException: couldn't save playlist item
        at uk.co.sentinelweb.cuer.app.orchestrator.PlaylistItemOrchestrator.save(PlaylistItemOrchestrator.kt:145)
        at uk.co.sentinelweb.cuer.app.orchestrator.PlaylistItemOrchestrator$save$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: playlist_item.media_id, playlist_item.playlist_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
        at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:730)
        at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:621)
        at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:47)
        at androidx.sqlite.db.framework.FrameworkSQLiteStatement.execute(FrameworkSQLiteStatement.java:41)
        at com.squareup.sqldelight.android.AndroidPreparedStatement.execute(AndroidSqliteDriver.kt:220)
        at com.squareup.sqldelight.android.AndroidSqliteDriver$execute$2.invoke(AndroidSqliteDriver.kt:142)
        at com.squareup.sqldelight.android.AndroidSqliteDriver$execute$2.invoke(AndroidSqliteDriver.kt:142)
        at com.squareup.sqldelight.android.AndroidSqliteDriver.execute(AndroidSqliteDriver.kt:127)
        at com.squareup.sqldelight.android.AndroidSqliteDriver.execute(AndroidSqliteDriver.kt:142)
        at uk.co.sentinelweb.cuer.app.db.database.PlaylistItemEntityQueriesImpl.create(DatabaseImpl.kt:1838)
        at uk.co.sentinelweb.cuer.db.repository.SqldelightPlaylistItemDatabaseRepository$save$2.invokeSuspend(SqldelightPlaylistItemDatabaseRepository.kt:65)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2022-10-28 16:50:35.636 10708-10708/uk.co.sentinelweb.cuer.app.debug E/Cuer: FATAL Global Exception
    java.lang.IllegalStateException: Save failed
        at uk.co.sentinelweb.cuer.app.ui.playlist_item_edit.PlaylistItemEditViewModel.commitPlaylistItems(PlaylistItemEditViewModel.kt:474)
        at uk.co.sentinelweb.cuer.app.ui.playlist_item_edit.PlaylistItemEditViewModel$commitPlaylistItems$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f367ec1, Dispatchers.Main.immediate]
    Caused by: uk.co.sentinelweb.cuer.app.orchestrator.OrchestratorContract$DatabaseException: couldn't save playlist item
        at uk.co.sentinelweb.cuer.app.orchestrator.PlaylistItemOrchestrator.save(PlaylistItemOrchestrator.kt:145)
        at uk.co.sentinelweb.cuer.app.orchestrator.PlaylistItemOrchestrator$save$1.invokeSuspend(Unknown Source:15)
        	... 10 more
     Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: playlist_item.media_id, playlist_item.playlist_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
        at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:730)
        at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:621)
        at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:47)
        at androidx.sqlite.db.framework.FrameworkSQLiteStatement.execute(FrameworkSQLiteStatement.java:41)
        at com.squareup.sqldelight.android.AndroidPreparedStatement.execute(AndroidSqliteDriver.kt:220)
        at com.squareup.sqldelight.android.AndroidSqliteDriver$execute$2.invoke(AndroidSqliteDriver.kt:142)
        at com.squareup.sqldelight.android.AndroidSqliteDriver$execute$2.invoke(AndroidSqliteDriver.kt:142)
        at com.squareup.sqldelight.android.AndroidSqliteDriver.execute(AndroidSqliteDriver.kt:127)
        at com.squareup.sqldelight.android.AndroidSqliteDriver.execute(AndroidSqliteDriver.kt:142)
        at uk.co.sentinelweb.cuer.app.db.database.PlaylistItemEntityQueriesImpl.create(DatabaseImpl.kt:1838)
        at uk.co.sentinelweb.cuer.db.repository.SqldelightPlaylistItemDatabaseRepository$save$2.invokeSuspend(SqldelightPlaylistItemDatabaseRepository.kt:65)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2022-10-28 16:50:35.738 10708-10740/uk.co.sentinelweb.cuer.app.debug D/TransportRuntime.SQLiteEventStore: Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
2022-10-28 16:50:35.741 10708-10740/uk.co.sentinelweb.cuer.app.debug D/TransportRuntime.JobInfoScheduler: Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=1771583033 in 1000ms(Backend next call timestamp 1666955166541). Attempt 1
2022-10-28 16:50:35.744 10708-10708/uk.co.sentinelweb.cuer.app.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: uk.co.sentinelweb.cuer.app.debug, PID: 10708
    java.lang.IllegalStateException: Save failed
        at uk.co.sentinelweb.cuer.app.ui.playlist_item_edit.PlaylistItemEditViewModel.commitPlaylistItems(PlaylistItemEditViewModel.kt:474)
        at uk.co.sentinelweb.cuer.app.ui.playlist_item_edit.PlaylistItemEditViewModel$commitPlaylistItems$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f367ec1, Dispatchers.Main.immediate]
    Caused by: uk.co.sentinelweb.cuer.app.orchestrator.OrchestratorContract$DatabaseException: couldn't save playlist item
        at uk.co.sentinelweb.cuer.app.orchestrator.PlaylistItemOrchestrator.save(PlaylistItemOrchestrator.kt:145)
        at uk.co.sentinelweb.cuer.app.orchestrator.PlaylistItemOrchestrator$save$1.invokeSuspend(Unknown Source:15)
        	... 10 more
     Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: playlist_item.media_id, playlist_item.playlist_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
        at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:730)
        at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:621)
        at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:47)
        at androidx.sqlite.db.framework.FrameworkSQLiteStatement.execute(FrameworkSQLiteStatement.java:41)
        at com.squareup.sqldelight.android.AndroidPreparedStatement.execute(AndroidSqliteDriver.kt:220)
        at com.squareup.sqldelight.android.AndroidSqliteDriver$execute$2.invoke(AndroidSqliteDriver.kt:142)
        at com.squareup.sqldelight.android.AndroidSqliteDriver$execute$2.invoke(AndroidSqliteDriver.kt:142)
        at com.squareup.sqldelight.android.AndroidSqliteDriver.execute(AndroidSqliteDriver.kt:127)
        at com.squareup.sqldelight.android.AndroidSqliteDriver.execute(AndroidSqliteDriver.kt:142)
        at uk.co.sentinelweb.cuer.app.db.database.PlaylistItemEntityQueriesImpl.create(DatabaseImpl.kt:1838)
        at uk.co.sentinelweb.cuer.db.repository.SqldelightPlaylistItemDatabaseRepository$save$2.invokeSuspend(SqldelightPlaylistItemDatabaseRepository.kt:65)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by sentinelweb** [comment]
fixed in #335
