### ISSUE TITLE
make playlist view MVI

### ISSUE THREAD

**Issue by sentinelweb** [sentinelweb/cuer#382]
- [x] convert to MVI
- [x] read playlist and display items
- [x] refactor Presenter code out
  - [x] checkToSave
  - [x] gotoPlaylist
  - [x] play
  - [x] playModeChange
  - [x] relatedItems
  - [x] pause - check on device
  - [x] resume - check on device
  - [x] showChannel
  - [x] showItem
  - [x] star
  - [x] starItem
- [x] playlist fragment in portrait player
- [x] do something with loading make placeholders

Additions
- [x] add share action button
- [x] add launch action button
- [x] android try making title text size smaller for longer titles. Also wrap.

bugs

- [ ] playlists with existing item dont import #344 
- [x] bug playlist doesnt load from browse
- [x] current item not highlighted on load
- [ ] crash below - not fixed #403 
- [x] in new playlist the title isnt under the header icons
- [x] new mark watched item flickers back on swipe
- [x] update listening post didnt refresh list after (even tho 2 new items) (pixel)
- [x] update eckart tolle playlist get errror "cant get playlist id" (emu)
- [x] delete an item (swipe) and it still shows until update
- [x] context menu is reloading or something in the portrait player - possibly the playingrefresh item is messing it up?
- [x] published date is always blank

**Comment by sentinelweb** [comment]
try to move (swipe) from the related items search

```
2023-01-11 22:00:17.752 7091-7091/uk.co.sentinelweb.cuer.app.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: uk.co.sentinelweb.cuer.app.debug, PID: 7091
    uk.co.sentinelweb.cuer.app.orchestrator.OrchestratorContract$DatabaseException: couldn't save playlist item
        at uk.co.sentinelweb.cuer.app.orchestrator.PlaylistItemOrchestrator.save(PlaylistItemOrchestrator.kt:145)
        at uk.co.sentinelweb.cuer.app.orchestrator.PlaylistItemOrchestrator$save$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f5a26c4, Dispatchers.Main]
    Caused by: java.lang.IllegalStateException: Save media failed vTyojqbW6lM
        at uk.co.sentinelweb.cuer.db.repository.SqldelightPlaylistItemDatabaseRepository$save$2.invokeSuspend(SqldelightPlaylistItemDatabaseRepository.kt:52)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by sentinelweb** [comment]
PR #393
