### ISSUE TITLE
issues after guid ids change

### ISSUE THREAD

**Issue by sentinelweb** [sentinelweb/cuer#417]
bugs from #403 
- [x] delete / close icon on playlist chip doesn't work
- [x] playlist click from player crash (st below) - fixed #419
- [x] move playlist by swipe crashes (st below 2) - fixed #419

**Comment by sentinelweb** [comment]
```
2023-02-06 15:34:15.876 26414-26414/uk.co.sentinelweb.cuer.app.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: uk.co.sentinelweb.cuer.app.debug, PID: 26414
    java.lang.IllegalArgumentException: Invalid parameter type: PLAYLIST_ID requires class java.lang.String (Kotlin reflection is not available) - was class uk.co.sentinelweb.cuer.app.orchestrator.OrchestratorContract$Identifier (Kotlin reflection is not available)
        at uk.co.sentinelweb.cuer.app.ui.common.navigation.NavigationModel.<init>(NavigationModel.kt:23)
        at uk.co.sentinelweb.cuer.app.ui.play_control.CastPlayerPresenter.onPlaylistClick(CastPlayerPresenter.kt:259)
        at uk.co.sentinelweb.cuer.app.ui.play_control.CastPlayerFragment.onViewCreated$lambda$7(CastPlayerFragment.kt:71)
        at uk.co.sentinelweb.cuer.app.ui.play_control.CastPlayerFragment.$r8$lambda$AEgFuPFgl-KOLTb2FbIeYpnLdYg(Unknown Source:0)
        at uk.co.sentinelweb.cuer.app.ui.play_control.CastPlayerFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7506)
        at android.view.View.performClickInternal(View.java:7483)
        at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
        at android.view.View$PerformClick.run(View.java:29341)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by sentinelweb** [comment]
```
2023-02-06 16:13:22.640 27734-27734/uk.co.sentinelweb.cuer.app.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: uk.co.sentinelweb.cuer.app.debug, PID: 27734
    java.lang.IllegalStateException: Playlist must have an id
        at uk.co.sentinelweb.cuer.app.ui.playlists.dialog.PlaylistsModelMapper.itemModel(PlaylistsModelMapper.kt:64)
        at uk.co.sentinelweb.cuer.app.ui.playlists.dialog.PlaylistsModelMapper.map(PlaylistsModelMapper.kt:30)
        at uk.co.sentinelweb.cuer.app.ui.playlists.dialog.PlaylistsDialogViewModel.executeRefresh(PlaylistsDialogViewModel.kt:113)
        at uk.co.sentinelweb.cuer.app.ui.playlists.dialog.PlaylistsDialogViewModel.access$executeRefresh(PlaylistsDialogViewModel.kt:25)
        at uk.co.sentinelweb.cuer.app.ui.playlists.dialog.PlaylistsDialogViewModel$executeRefresh$1.invokeSuspend(Unknown Source:14)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@bcd864c, Dispatchers.Main]
```
