### ISSUE TITLE
allow playing app playlists

### ISSUE THREAD

**Issue by sentinelweb** [sentinelweb/cuer#446]
- [x] need to send playlist id to `playUseCase` to pass into queue
- [x] check playback is ok
- [x] check all app playlists play
- [x] limit playmode to single for app playlists (hide button)
- [x] disable play button if playlist is empty (still show it)
- [x] bug: cant navigate back from playlist item edit to search (asks to save first)
- [ ] bug: playing item doesnt goto to player on startup (when playing on chromecast) - when playling app playlist
- [x] remove: click item thimb to play on playing playlist has toast "please add item first"
- [x] update qmediator test media position update if memory (wont update)
- [x] when video reaches ends on yt search then it returns to start of playlist (cos: currentItem not updated?) 
     - possibly just happened because of app restart
- [x] check share playlist still works properly
- [x] bug: update media data to get duration when moving to new playlist - results from search have no duration so seekbar doesnt work
- [x] bug: diagnose exception below (crash null id )
- [x] disable seek if there is no duration
- [x] items not being marked as watched when played on normal playlists?
- [x] seekbar is enabled for live broadcasts
- [x] fix liveStreamingDetails exception below
- [ ] share play add didnt work :( share playt add should switch the playlist to the selected playlist (e.g awaay from new) 
     - (#313 reopened)
- [x] when new playlist was refreshed the play indicator showed for the wrong item (highlight item should pass the id of the playlist item)
- [ ] click on the player item icon passed the item from the new playlist (refresh the item from the db in PlaylistItemEdit on load if local) - maybe just pass the id of the item rather than the whole item
     - #452 
- [x] click thumb of item in new should passes the item playlist
- [x] bug : seekbar diabled for non live broadcasts on ccast
- [x] Youtube search play disabled - too many issues (mainly updating duration)

**Comment by sentinelweb** [comment]
- [ ] icon on play button doesn't tint properly when disabled (leaving)

**Comment by sentinelweb** [comment]
got this exception : try to diagnose
https://console.firebase.google.com/project/cuer-275020/crashlytics/app/android:uk.co.sentinelweb.cuer.app.debug/issues/18835a238d694ee4ce800dacea0f5805?time=last-hour&sessionEventKey=63F77971016500012DC68B0E489FD547_1781815198663293522

NPE:
uk.co.sentinelweb.cuer.app.orchestrator.memory.PlaylistMemoryRepository$PlayListItemMemoryRepository.loadList (PlaylistMemoryRepository.kt:138)
uk.co.sentinelweb.cuer.app.orchestrator.PlaylistItemOrchestrator.loadList (PlaylistItemOrchestrator.kt:43)
uk.co.sentinelweb.cuer.app.ui.playlist_item_edit.PlaylistItemEditViewModel$setData$2.invokeSuspend (PlaylistItemEditViewModel.kt:147)

**Comment by sentinelweb** [comment]
```
Caused by: kotlinx.serialization.MissingFieldException: Fields [actualEndTime, scheduledStartTime, scheduledEndTime, activeLiveChatId] are required for type with serial name 'uk.co.sentinelweb.cuer.net.youtube.videos.dto.YoutubeVideosDto.VideoDto.LiveStreamingDetailsDto', but they were missing at path: $.items[0].liveStreamingDetails at path: $.items[0].liveStreamingDetails at path: $.items[0].liveStreamingDetails at path: $.items[0].liveStreamingDetails
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:2)
                                                                                                    	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:3)
                                                                                                    	at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:9)
                                                                                                    	at io.ktor.serialization.ContentConverterKt$deserialize$$inlined$map$1$2.emit(Emitters.kt:8) 
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:6) 
                                                                                                    	at io.ktor.serialization.ContentConverterKt$deserialize$$inlined$map$1.collect(SafeCollector.common.kt:1) 
                                                                                                    	at kotlinx.coroutines.flow.FlowKt.firstOrNull(Unknown Source:7) 
                                                                                                    	at io.ktor.serialization.ContentConverterKt.deserialize(ContentConverter.kt:6) 
                                                                                                    	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invokeSuspend(ContentNegotiation.kt:29) 
                                                                                                    	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(ContentNegotiation.kt:1) 
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:8) 
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:4) 
                                                                                                    	at io.ktor.client.HttpClient$4.invokeSuspend(HttpClient.kt:4) 
                                                                                                    	at io.ktor.client.HttpClient$4.invoke(HttpClient.kt:1) 
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:8) 
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:4) 
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:2) 
                                                                                                    	at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:4) 
                                                                                                    	at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(HttpCallValidator.kt:1) 
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:8) 
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:4) 
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:5) 
                                                                                                    	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:6) 
                                                                                                    	at io.ktor.client.call.HttpClientCall.bodyNullable(HttpClientCall.kt:16) 
                                                                                                    	at uk.co.sentinelweb.cuer.net.youtube.YoutubeService.getVideoInfos$netKmm_release(YoutubeService.kt:29) 
                                                                                                    	at uk.co.sentinelweb.cuer.net.youtube.YoutubeService$getVideoInfos$1.invokeSuspend(Unknown Source:17) 
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3) 
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18) 
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2) 
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10) 
                                                                                                    
```

**Comment by sentinelweb** [comment]
```
Fatal Exception: java.lang.IllegalStateException: FragmentPlaylistItemEditBinding not bound
       at uk.co.sentinelweb.cuer.app.ui.playlist_item_edit.PlaylistItemEditFragment.getBinding(PlaylistItemEditFragment.kt:73)
       at uk.co.sentinelweb.cuer.app.ui.playlist_item_edit.PlaylistItemEditFragment.access$getBinding(PlaylistItemEditFragment.java:53)
       at uk.co.sentinelweb.cuer.app.ui.playlist_item_edit.PlaylistItemEditFragment$onViewCreated$4.onOffsetChanged(PlaylistItemEditFragment.kt:179)
       at com.google.android.material.appbar.AppBarLayout.onOffsetChanged(AppBarLayout.java:810)
       at com.google.android.material.appbar.AppBarLayout$BaseBehavior.setHeaderTopBottomOffset(AppBarLayout.java:1954)
       at com.google.android.material.appbar.AppBarLayout$BaseBehavior.setHeaderTopBottomOffset(AppBarLayout.java:1345)
       at com.google.android.material.appbar.HeaderBehavior.setHeaderTopBottomOffset(HeaderBehavior.java:158)
       at com.google.android.material.appbar.AppBarLayout$BaseBehavior$1.onAnimationUpdate(AppBarLayout.java:1538)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1653)
       at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1440)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1572)
```

**Comment by sentinelweb** [comment]
- [ ] notification exception to do with indexes
```
FATAL EXCEPTION: main
Process: uk.co.sentinelweb.cuer.app, PID: 14101
                                                                                                    android.app.RemoteServiceException$BadForegroundServiceNotificationException: Bad notification(tag=null, id=34564) posted from package uk.co.sentinelweb.cuer.app, crashing app(uid=10313, pid=14101): Couldn't inflate contentViewsjava.lang.IndexOutOfBoundsException: Index: 4, Size: 4
at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1985)
at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2241)
at android.os.Handler.dispatchMessage(Handler.java:106)
