### ISSUE TITLE
remote playback

### ISSUE THREAD

**Issue by sentinelweb** [sentinelweb/cuer#457]
- [ ] Replace chromecast icon with a route icon - pops up a dialog to reroute playback
- [ ] Make a framework to connect to a remote device
- [ ] Control player over webserver

**Comment by sentinelweb** [comment]
also this error: occured in hotel where multi-ping works but i think http comms must be blocked
```
FATAL EXCEPTION: DefaultDispatcher-worker-9
                                                                                                    Process: uk.co.sentinelweb.cuer.app.debug, PID: 22262
                                                                                                    java.net.NoRouteToHostException: No route to host
                                                                                                    	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
                                                                                                    	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:762)
                                                                                                    	at io.ktor.network.sockets.SocketImpl.connect$ktor_network(SocketImpl.kt:50)
                                                                                                    	at io.ktor.network.sockets.SocketImpl$connect$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f4d2061, Dispatchers.IO]
```

**Comment by sentinelweb** [comment]
occurred on android trying to start server on port 80

```
FATAL EXCEPTION: DefaultDispatcher-worker-1
 Process: uk.co.sentinelweb.cuer.app.debug, PID: 25646
 java.net.SocketException: Permission denied
at sun.nio.ch.Net.bind0(Native Method)
at sun.nio.ch.Net.bind(Net.java:442)
at sun.nio.ch.Net.bind(Net.java:434)
at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
at io.ktor.network.sockets.ConnectUtilsJvmKt.bind(ConnectUtilsJvm.kt:35)
at io.ktor.network.sockets.TcpSocketBuilder.bind(TcpSocketBuilder.kt:45)
at io.ktor.network.sockets.TcpSocketBuilder.bind(TcpSocketBuilder.kt:29)
at io.ktor.network.sockets.TcpSocketBuilder.bind$default(TcpSocketBuilder.kt:25)
at io.ktor.server.cio.backend.HttpServerKt$httpServer$acceptJob$1.invokeSuspend(HttpServer.kt:48)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
```
