### ISSUE TITLE
exceptions to fix - autobackup

### ISSUE THREAD

**Issue by sentinelweb** [sentinelweb/cuer#491]
looks to be an exception when generatinig the auto-backup file - drop to disk.

**Comment by sentinelweb** [comment]
Error backing up
                                                                                                    java.lang.OutOfMemoryError: Failed to allocate a 156447040 byte allocation with 25165824 free bytes and 132MB until OOM, target footprint 154260128, growth limit 268435456
                                                                                                    	at java.util.Arrays.copyOf(Arrays.java:3681)
                                                                                                    	at kotlinx.serialization.json.internal.JsonToStringWriter.ensureTotalCapacity(JsonToStringWriter.kt:132)
                                                                                                    	at kotlinx.serialization.json.internal.JsonToStringWriter.ensureAdditionalCapacity(JsonToStringWriter.kt:125)
                                                                                                    	at kotlinx.serialization.json.internal.JsonToStringWriter.write(JsonToStringWriter.kt:45)
                                                                                                    	at kotlinx.serialization.json.internal.Composer.print(Composers.kt:37)
                                                                                                    	at kotlinx.serialization.json.internal.ComposerWithPrettyPrint.nextItem(Composers.kt:92)
                                                                                                    	at kotlinx.serialization.json.internal.ComposerWithPrettyPrint.nextItemIfNotFirst(Composers.kt:97)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonEncoder.endStructure(StreamingJsonEncoder.kt:99)
                                                                                                    	at uk.co.sentinelweb.cuer.domain.GUID$$serializer.serialize(GUID.kt:5)
                                                                                                    	at uk.co.sentinelweb.cuer.domain.GUID$$serializer.serialize(GUID.kt:5)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:249)
                                                                                                    	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
                                                                                                    	at uk.co.sentinelweb.cuer.app.orchestrator.OrchestratorContract$Identifier.write$Self$domain_debug(OrchestratorContract.kt:18)
                                                                                                    	at uk.co.sentinelweb.cuer.app.orchestrator.OrchestratorContract$Identifier$$serializer.serialize(OrchestratorContract.kt:18)
                                                                                                    	at uk.co.sentinelweb.cuer.app.orchestrator.OrchestratorContract$Identifier$$serializer.serialize(OrchestratorContract.kt:18)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:249)
                                                                                                    	at kotlinx.serialization.encoding.Encoder$DefaultImpls.encodeNullableSerializableValue(Encoding.kt:299)
                                                                                                    	at kotlinx.serialization.encoding.AbstractEncoder.encodeNullableSerializableValue(AbstractEncoder.kt:18)
                                                                                                    	at kotlinx.serialization.encoding.AbstractEncoder.encodeNullableSerializableElement(AbstractEncoder.kt:90)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeNullableSerializableElement(StreamingJsonEncoder.kt:155)
                                                                                                    	at uk.co.sentinelweb.cuer.domain.ChannelDomain.write$Self$domain_debug(ChannelDomain.kt:8)
                                                                                                    	at uk.co.sentinelweb.cuer.domain.ChannelDomain$$serializer.serialize(ChannelDomain.kt:8)
                                                                                                    	at uk.co.sentinelweb.cuer.domain.ChannelDomain$$serializer.serialize(ChannelDomain.kt:8)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:249)
                                                                                                    	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
                                                                                                    	at uk.co.sentinelweb.cuer.domain.MediaDomain.write$Self$domain_debug(MediaDomain.kt:9)
                                                                                                    	at uk.co.sentinelweb.cuer.domain.MediaDomain$$serializer.serialize(MediaDomain.kt:9)
                                                                                                    	at uk.co.sentinelweb.cuer.domain.MediaDomain$$serializer.serialize(MediaDomain.kt:9)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:249)
                                                                                                    	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
                                                                                                    	at uk.co.sentinelweb.cuer.domain.PlaylistItemDomain.write$Self$domain_debug(PlaylistItemDomain.kt:8)
                                                                                                    	at uk.co.sentinelweb.cuer.domain.PlaylistItemDomain$$serializer.serialize(PlaylistItemDomain.kt:8)
                                                                                                    	at uk.co.sentinelweb.cuer.domain.PlaylistItemDomain$$serializer.serialize(PlaylistItemDomain.kt:8)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:249)
                                                                                                    	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
                                                                                                    	at kotlinx.serialization.internal.CollectionLikeSerializer.serialize(CollectionSerializers.kt:69)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:249)
                                                                                                    	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
2024-11-06 21:50:14.222 31779-31976 BackupFileManager       uk.co.sentinelweb.cuer.app.debug     E  	at uk.co.sentinelweb.cuer.domain.PlaylistDomain.write$Self$domain_debug(PlaylistDomain.kt:11)
                                                                                                    	at uk.co.sentinelweb.cuer.domain.PlaylistDomain$$serializer.serialize(PlaylistDomain.kt:11)
                                                                                                    	at uk.co.sentinelweb.cuer.domain.PlaylistDomain$$serializer.serialize(PlaylistDomain.kt:11)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:249)
                                                                                                    	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
                                                                                                    	at kotlinx.serialization.internal.CollectionLikeSerializer.serialize(CollectionSerializers.kt:69)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:249)
                                                                                                    	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
                                                                                                    	at uk.co.sentinelweb.cuer.domain.backup.BackupFileModel.write$Self$domain_debug(BackupFileModel.kt:7)
                                                                                                    	at uk.co.sentinelweb.cuer.domain.backup.BackupFileModel$$serializer.serialize(BackupFileModel.kt:7)
                                                                                                    	at uk.co.sentinelweb.cuer.domain.backup.BackupFileModel$$serializer.serialize(BackupFileModel.kt:7)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:249)
                                                                                                    	at kotlinx.serialization.json.internal.JsonStreamsKt.encodeByWriter(JsonStreams.kt:31)
                                                                                                    	at kotlinx.serialization.json.Json.encodeToString(Json.kt:81)
                                                                                                    	at uk.co.sentinelweb.cuer.domain.ext.SerializationExtKt.serialise(SerializationExt.kt:94)
                                                                                                    	at uk.co.sentinelweb.cuer.app.backup.BackupFileManager$backupDataJson$2.invokeSuspend(BackupFileManager.kt:79)
                                                                                                    	at uk.co.sentinelweb.cuer.app.backup.BackupFileManager$backupDataJson$2.invoke(Unknown Source:8)
                                                                                                    	at uk.co.sentinelweb.cuer.app.backup.BackupFileManager$backupDataJson$2.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:42)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:164)
                                                                                                    	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
                                                                                                    	at uk.co.sentinelweb.cuer.app.backup.BackupFileManager.backupDataJson(BackupFileManager.kt:74)
                                                                                                    	at uk.co.sentinelweb.cuer.app.backup.BackupFileManager.access$backupDataJson(BackupFileManager.kt:25)
                                                                                                    	at uk.co.sentinelweb.cuer.app.backup.BackupFileManager$makeBackupZipFile$2.invokeSuspend(BackupFileManager.kt:49)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)

**Comment by sentinelweb** [comment]
FATAL EXCEPTION: pool-6-thread-8
                                                                                                    Process: uk.co.sentinelweb.cuer.app.debug, PID: 31779
                                                                                                    java.lang.NoClassDefFoundError: com.google.android.datatransport.cct.internal.AutoBatchedLogRequestEncoder$BatchedLogRequestEncoder
                                                                                                    	at com.google.android.datatransport.cct.internal.AutoBatchedLogRequestEncoder.configure(AutoBatchedLogRequestEncoder.java:21)
                                                                                                    	at com.google.firebase.encoders.json.JsonDataEncoderBuilder.configureWith(JsonDataEncoderBuilder.java:103)
                                                                                                    	at com.google.android.datatransport.cct.internal.BatchedLogRequest.createDataEncoder(BatchedLogRequest.java:39)
                                                                                                    	at com.google.android.datatransport.cct.CctTransportBackend.<init>(CctTransportBackend.java:100)
                                                                                                    	at com.google.android.datatransport.cct.CctTransportBackend.<init>(CctTransportBackend.java:129)
                                                                                                    	at com.google.android.datatransport.cct.CctBackendFactory.create(CctBackendFactory.java:29)
                                                                                                    	at com.google.android.datatransport.runtime.backends.MetadataBackendRegistry.get(MetadataBackendRegistry.java:80)
                                                                                                    	at com.google.android.datatransport.runtime.scheduling.DefaultScheduler.lambda$schedule$1(DefaultScheduler.java:70)
                                                                                                    	at com.google.android.datatransport.runtime.scheduling.DefaultScheduler$$Lambda$1.run(Unknown Source:8)
                                                                                                    	at com.google.android.datatransport.runtime.SafeLoggingExecutor$SafeLoggingRunnable.run(SafeLoggingExecutor.java:47)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.NoSuchMethodError: No static method of(Ljava/lang/String;)Lcom/google/firebase/encoders/FieldDescriptor; in class Lcom/google/firebase/encoders/FieldDescriptor; or its super classes (declaration of 'com.google.firebase.encoders.FieldDescriptor' appears in /data/app/~~DlqNWenmIPlS3LnaShau0Q==/uk.co.sentinelweb.cuer.app.debug-JHCvM4dgs-yadAg_SNduEA==/base.apk!classes36.dex)
                                                                                                    	at com.google.android.datatransport.cct.internal.AutoBatchedLogRequestEncoder$BatchedLogRequestEncoder.<clinit>(AutoBatchedLogRequestEncoder.java:38)
                                                                                                    	at com.google.android.datatransport.cct.internal.AutoBatchedLogRequestEncoder.configure(AutoBatchedLogRequestEncoder.java:21) 
                                                                                                    	at com.google.firebase.encoders.json.JsonDataEncoderBuilder.configureWith(JsonDataEncoderBuilder.java:103) 
                                                                                                    	at com.google.android.datatransport.cct.internal.BatchedLogRequest.createDataEncoder(BatchedLogRequest.java:39) 
                                                                                                    	at com.google.android.datatransport.cct.CctTransportBackend.<init>(CctTransportBackend.java:100) 
                                                                                                    	at com.google.android.datatransport.cct.CctTransportBackend.<init>(CctTransportBackend.java:129) 
                                                                                                    	at com.google.android.datatransport.cct.CctBackendFactory.create(CctBackendFactory.java:29) 
                                                                                                    	at com.google.android.datatransport.runtime.backends.MetadataBackendRegistry.get(MetadataBackendRegistry.java:80) 
                                                                                                    	at com.google.android.datatransport.runtime.scheduling.DefaultScheduler.lambda$schedule$1(DefaultScheduler.java:70) 
                                                                                                    	at com.google.android.datatransport.runtime.scheduling.DefaultScheduler$$Lambda$1.run(Unknown Source:8) 
                                                                                                    	at com.google.android.datatransport.runtime.SafeLoggingExecutor$SafeLoggingRunnable.run(SafeLoggingExecutor.java:47) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
2024-11-06 21:50:10.419 31779-32226 Cuer                    uk.co.sentinelweb.cuer.app.debug     E  FATAL Global Exception
                                                                                                    java.lang.NoClassDefFoundError: com.google.android.datatransport.cct.internal.AutoBatchedLogRequestEncoder$BatchedLogRequestEncoder
                                                                                                    	at com.google.android.datatransport.cct.internal.AutoBatchedLogRequestEncoder.configure(AutoBatchedLogRequestEncoder.java:21)
                                                                                                    	at com.google.firebase.encoders.json.JsonDataEncoderBuilder.configureWith(JsonDataEncoderBuilder.java:103)
                                                                                                    	at com.google.android.datatransport.cct.internal.BatchedLogRequest.createDataEncoder(BatchedLogRequest.java:39)
                                                                                                    	at com.google.android.datatransport.cct.CctTransportBackend.<init>(CctTransportBackend.java:100)
                                                                                                    	at com.google.android.datatransport.cct.CctTransportBackend.<init>(CctTransportBackend.java:129)
                                                                                                    	at com.google.android.datatransport.cct.CctBackendFactory.create(CctBackendFactory.java:29)
                                                                                                    	at com.google.android.datatransport.runtime.backends.MetadataBackendRegistry.get(MetadataBackendRegistry.java:80)
                                                                                                    	at com.google.android.datatransport.runtime.scheduling.DefaultScheduler.lambda$schedule$1(DefaultScheduler.java:70)
                                                                                                    	at com.google.android.datatransport.runtime.scheduling.DefaultScheduler$$Lambda$1.run(Unknown Source:8)
                                                                                                    	at com.google.android.datatransport.runtime.SafeLoggingExecutor$SafeLoggingRunnable.run(SafeLoggingExecutor.java:47)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.NoSuchMethodError: No static method of(Ljava/lang/String;)Lcom/google/firebase/encoders/FieldDescriptor; in class Lcom/google/firebase/encoders/FieldDescriptor; or its super classes (declaration of 'com.google.firebase.encoders.FieldDescriptor' appears in /data/app/~~DlqNWenmIPlS3LnaShau0Q==/uk.co.sentinelweb.cuer.app.debug-JHCvM4dgs-yadAg_SNduEA==/base.apk!classes36.dex)
                                                                                                    	at com.google.android.datatransport.cct.internal.AutoBatchedLogRequestEncoder$BatchedLogRequestEncoder.<clinit>(AutoBatchedLogRequestEncoder.java:38)
                                                                                                    	at com.google.android.datatransport.cct.internal.AutoBatchedLogRequestEncoder.configure(AutoBatchedLogRequestEncoder.java:21) 
                                                                                                    	at com.google.firebase.encoders.json.JsonDataEncoderBuilder.configureWith(JsonDataEncoderBuilder.java:103) 
                                                                                                    	at com.google.android.datatransport.cct.internal.BatchedLogRequest.createDataEncoder(BatchedLogRequest.java:39) 
                                                                                                    	at com.google.android.datatransport.cct.CctTransportBackend.<init>(CctTransportBackend.java:100) 
                                                                                                    	at com.google.android.datatransport.cct.CctTransportBackend.<init>(CctTransportBackend.java:129) 
                                                                                                    	at com.google.android.datatransport.cct.CctBackendFactory.create(CctBackendFactory.java:29) 
                                                                                                    	at com.google.android.datatransport.runtime.backends.MetadataBackendRegistry.get(MetadataBackendRegistry.java:80) 
                                                                                                    	at com.google.android.datatransport.runtime.scheduling.DefaultScheduler.lambda$schedule$1(DefaultScheduler.java:70) 
                                                                                                    	at com.google.android.datatransport.runtime.scheduling.DefaultScheduler$$Lambda$1.run(Unknown Source:8) 
                                                                                                    	at com.google.android.datatransport.runtime.SafeLoggingExecutor$SafeLoggingRunnable.run(SafeLoggingExecutor.java:47) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
2024-11-06 21:50:13.014 31779-32184 SQLiteConnectionPool    uk.co.sentinelweb.cuer.app.debug     W

**Comment by sentinelweb** [comment]
fixed in #492
